# Generated by Django 4.1 on 2024-06-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.IntegerField()),
                ('breed', models.CharField(max_length=50)),
                ('animal_age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('body_condition', models.CharField(max_length=50)),
            ],
        ),
    ]
